---
title: "get ncdfs"
author: "Dana K Briscoe"
date: '`r Sys.Date()`'
output: html_document
params:
  node: "swfsc" 
  url: "https://coastwatch.pfeg.noaa.gov/erddap/griddap/"
  eov: "chla"
  varname: "chlor_a"
  dataset_ID: "nesdisVHNnoaaSNPPnoaa20NRTchlaGapfilledDaily"
  enddate: !r Sys.Date() - 2
  startdate: !r as.Date('2023-07-10')
  timestep: "day"
  alt: "NULL"
  nc_path: "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/npac"
  bbox: !r tibble::tibble(ymin=20, ymax=50,xmin=-180, xmax=-110)

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE,
    dpi = 300,
    fig.align = "center",
    fig.height = 9
    )

# See Options: knitr::opts_chunk$get()
```

```{r load-libraries}
# Load Libraries ---
# library(RNetCDF)
library(tidyverse)
library(ncdf4)
library(lubridate)


```

```{r source-helper-funcs}
## Source helper functions
source('00_automate_EOV_helper_functions.R')

```

```{r set-dateRange}
dates <- getDateRange(startdate = params$startdate,enddate = params$enddate, unit=params$timestep) 
```

```{r set-param-datasetID}
if(params$eov == "sst"){
    node <- 'pacioos'
    url <- 'https://pae-paha.pacioos.hawaii.edu/erddap/griddap/'
    varname  <- "CRW_SST"
    dataset_ID <- "dhw_5km"
    
    dates <- dates %>%
    as.character() %>%
    str_c(., 'T12:00:00Z', sep=" ")
    # params$bbox <- params$bbox %>% mutate(xmin = make360(xmin), xmax = make360(xmax)) %>% as.data.frame()
    alt = NULL
} else if(params$eov == "ssta"){ 
    node <- 'pacioos'
    url <- 'https://pae-paha.pacioos.hawaii.edu/erddap/griddap/'
    varname  <- "CRW_SSTANOMALY"
    dataset_ID <- "dhw_5km"
    
    dates <- dates %>%
    as.character() %>%
    str_c(., 'T12:00:00Z', sep="")
    # params$bbox <- params$bbox %>% mutate(xmin = make360(xmin), xmax = make360(xmax)) %>% as.data.frame()
    alt = NULL
} else if(params$eov == "chla"){
    node <- 'swfsc'
    url <- 'https://coastwatch.pfeg.noaa.gov/erddap/griddap/'
    varname  <- "chlor_a"
    dataset_ID <- "nesdisVHNnoaaSNPPnoaa20NRTchlaGapfilledDaily"
    
    dates <- dates[dates <= (Sys.Date() - 4)] # fyi, latest product is 4 days behind current
    as.character() %>%
    str_c(., 'T12:00:00Z', sep="")
    # params$bbox <- params$bbox %>% mutate(xmin = make180(xmin), xmax = make180(xmax)) 
    alt = 0
    

}
```

```{r get-ncdfs}

## dkb note -- add alt string [(0):1:(0)] between long and lats (see scratch)
for (i in 1:length(dates)) {
  tryCatch({
    getNCDF(
    url = params$url,
    eov = params$eov,
    varname = params$varname,
    dataset_ID = params$dataset_ID, 
    bbox = params$bbox, 
    dt = dates[i], 
    alt = alt,
    ncpath = params$nc_path
  )
  }, error = function(e){
      message('Caught an error!')
      print(e)
  }
  )
}
```


