---
title: "animate cc eov"
author: "Dana K Briscoe"
date: '`r Sys.Date()`'
output: html_document
params:
  eov: "MBchla8day_LonPM180"
  enddate: !r Sys.Date() - 2
  startdate: !r as.Date('2023-07-10')
  timestep: "weekly"
  nc_path: "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/npac"
  bbox: !r tibble::tibble(ymin=25, ymax=50,xmin=-170, xmax=-110)
  cclme: TRUE
  tcms: TRUE
  bathy: TRUE
  state_borders: TRUE
  subset_tcms: TRUE
  plot_text_size: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE #,
    # dpi = 300,
    # fig.align = "center",
    # fig.height = 9
    )

# See Options: knitr::opts_chunk$get()
```

```{r load-libraries}
library(tidyverse)
library(data.table)
library(sp)
library(sf)
library(gganimate)
library(ggmap)
library(dplyr)
library(lubridate)
library(magrittr)
library(magick)
library(raster)
library(oce)
library(RColorBrewer)
library(rnaturalearth)
library(gifski)
library(magick)
library(gtools)

```

```{r source-helper-funcs}
## Source helper functions
source('00_automate_EOV_helper_functions.R')
source('crop_image.R')
```


## Load CC Data ----
```{r load-raw-cc-data}
## Pull Raw Tracking Data -----
files <- list.files('~/Downloads/batch/', pattern = "All.csv", recursive=T, full.names=T)

raw_data <- rbindlist(lapply(files, fread)) %>%
    dplyr::select('Platform ID No.', 'Latitude', 'Longitude', 'Loc. quality', 'Loc. date') %>%
    rename(id = 1,
           lat = 2,
           lon = 3,
           loc_quality = 4,
           date = 5
    ) %>%
    mutate(date = as.POSIXct(date, format= "%m/%d/%Y %H:%M:%S", tz="UTC")) %>%
    filter(lat > 0 & lat < 60) %>%
    filter(date >= '2023-07-11 04:30:00') %>%
    
    filter(loc_quality != 0)  # added 17 Jan 2024 -- to deal with raw argos bad data point (tsubaki, 12 jan 2024 locs - remove loc class = 0)


```


## Prep CC Data
```{r source-load-cohort1-routine}
source('01_prep_wc_data.R')

```

```{r 01-rename dfs}
raw_df <- raw_data_cohort_1_w_names
daily_avg_data <- daily_avg_data_cohort_1 

# misc - pull uniqud id info for later?
ids = unique(daily_avg_data$id) # prefer to use t names instead
# ids = unique(daily_avg_data$turtle_name)

t_names = unique(daily_avg_data$turtle_name)
t_nums = unique(daily_avg_data$turtle_num)
t_names_num <- c(str_c(t_nums, ' - ', t_names))
```

```{r prep-turtle-sp}
turtlesgeo <- prep_turtles_sp(df = daily_avg_data)

```


## Load EOV Data ---
```{r set-param-ncpath}
# Set param to run
if(params$eov == 'sst'){
    nc_path <- "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/deploy_reports"
    varname <- "sst_dhw_5km"
} else if (params$eov == "ssta"){
    nc_path <- "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/npac"
    varname <- "ssta_dhw_5km"
} else if (params$eov == "chlaWeekly"){
    nc_path <- "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/npac"
    varname <- "chlaWeekly" 
} else if(params$eov == "MBchla8day_LonPM180"){
    nc_path <- "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/npac"
   varname <- "MBchla8day_LonPM180" 
}

```

```{r get-ncdf-list}
# get ncdf list

ncs <- list.files(nc_path, pattern = varname, full.names=T)
print(str_c('most recent ncdf - ', ncs[length(ncs)]))

```

```{r get-nc-fdates}
fdates <- get_ncdf_fdates(x = params$eov, ncs)

```


```{r get-cc-eov-date-intersection}
# get dates that match track dates
tracking_dates <- unique(daily_avg_data$date)
eov_dates <- as.Date(unique(fdates))
deploy_date <- as.Date("2023-07-10")

daily_dates <- intersect(as.character(tracking_dates), as.character(eov_dates))
```


```{r load-intersecting-ncdfs}
# get files
ncIn <- sapply(1:length(daily_dates), function(x) ncs[grepl(daily_dates[x],ncs)])

# convert ncs to raster stack
ras <- {suppressWarnings(raster::stack(ncIn))}

```


## Prep EOV Data
### Prep / Crop Rasters
```{r assign-ras-date-names}
# reassign ras names according to intersecting cc-eov dates (assuming n lengths differ)
if(length(fdates) != length(ncIn)){

    if(params$eov == 'sst'){
        nc_dates <- ncIn %>% 
            map(~parseDT(., idx = 6, start=13, stop = 22, format="%Y-%m-%d")) %>%
            unlist() %>% as.Date() #%>%
    } else if (params$eov == 'chlaWeekly'){
        nc_dates <- ncIn %>% 
            map(~parseDT(., idx = 6, start=28, stop = 38, format="%Y-%m-%d")) %>%
            unlist() %>% as.Date() #%>%
    } else if(params$eov == 'ssta'){
        nc_dates <- ncIn %>% 
            map(~parseDT(., idx = 6, start=14, stop = 23, format="%Y-%m-%d")) %>%
            unlist() %>% as.Date() #%>%
    } else if(params$eov == 'MBchla8day_LonPM180'){
        nc_dates <- ncIn %>% 
            map(~parseDT(., idx = 6, start=29, stop = 38, format="%Y-%m-%d")) %>%
            unlist() %>% as.Date() #%>%
    }
    
    names(ras) <- nc_dates

} else {
    names(ras) <- nc_dates  # double check this works.
    print('confirm fdates')
}

```

```{r set-spatial-extents}
e180 <- extent(params$bbox[['xmin']], params$bbox[['xmax']], params$bbox[['ymin']], params$bbox[['ymax']])
# e360 <- extent(make360(e[1]), make360(e[2]), e[3], e[4])   

```

```{r crop-ras-extent}
ras_subset <- crop(ras, e180) 
```

### GoC Mask
```{r mask-GoC}
# create goc mask
# goc_mask <- rbind(c(-110, 23.75), c(-122, 40), c(-110, 40), c(-110, 23.75))
goc_mask <- rbind(c(-106, 18), c(-110, 23.75), c(-122, 40), c(-110, 40), c(-106, 18))
goc_mask <- SpatialPolygons(list(Polygons(list(Polygon(goc_mask)), 1)))

# mask raster stack
ras_masked <- mask(ras_subset, goc_mask, inverse=T)
```

### Ras to DF
```{r convert-ras-to-df}

eov_df <- ras_masked %>%
    ras2df()

```


## Prep Plots --------
### Prep CC-EOV DFs

```{r create-turtles-df}
turtles_df <- turtlesgeo %>% filter(date %in% nc_dates)
```


```{r calc-df-timesteps}
if(params$timestep == 'daily'){
    
    # keep daily avgs and filter last 1 month for anim
    turtles_df_daily <- turtles_df %>%
        filter(date >= params$startdate & date <= params$enddate)
    
    eov_df_daily <- eov_df %>%
        filter(date >= params$startdate & date <=params$enddate)
    
    
} else if(params$timestep == 'weekly'){
    # convert daily avgs to weekly dates for anim
    turtles_df_weekly <- turtles_df %>%
        mutate(start_of_week = floor_date(date, "week") %>% as.Date(.)) %>%
        group_by(start_of_week, id) %>%
        summarize(lat = mean(lat, na.rm = TRUE),
                  lon = mean(lon, na.rm = TRUE), .groups = "drop") %>%
        rename('date' = 'start_of_week')
    
    eov_df_weekly <- eov_df %>%
        mutate(start_of_week = floor_date(date, "week") %>% as.Date(.)) %>%
        group_by(start_of_week, x, y) %>%
        summarize(val = mean(val, na.rm = TRUE), .groups = "drop") %>%
        rename('date' = 'start_of_week')

}

```

```{r rename-cc-eov-dfs-for-anim}
# rename df's for anim plotting
## cc

if(exists("turtles_df_daily")){
    turtles_df_anim <- turtles_df_daily
} else if(exists("turtles_df_weekly")){
    turtles_df_anim <- turtles_df_weekly
}

## eov
if(exists("eov_df_daily")){
    eov_df_anim <- eov_df_daily
} else if(exists("eov_df_weekly")){
    eov_df_anim <- eov_df_weekly
}

```


### Set EOV CBAR Params
```{r set-eov-cbar-params}

if(params$eov == 'sst'){
    
    limits = c(5,35)
    
    # goc masked
    cbar_breaks = seq(4, 30, 1)
    cbar_limits = c(4, 31)
    # cbar_limits <- c(6,31)
    cbar_int <- 1
    cbar_title <- 'SST (째C)'
    
    tzcf_contour = 18
    tzcf_color = 'white'
        
    tcms_color = "#FFFCF2"
    
    smooth_rainbow <- khroma::colour("smooth rainbow")

    cpal <- c(smooth_rainbow(length(seq(floor(limits[1]), ceiling(limits[2]), 1)), range = c(0, 0.9)), "#9e2a2b", "firebrick4")
    
    zCuts <- seq(4,34,1)
    
} else if(params$eov == 'ssta'){
    
    # limits = c(5,35)
    
    tzcf_contour <- NA
    tzcf_color = NA
    
    tcms_color = "gray40"
    
    cbar_breaks <- seq(-5.5,6,0.5)
    cbar_limits <- c(-5.5,6)
    cbar_int <- 0.5
    cbar_title <- 'SST (째C)\n'

    cpal <- rev(c("#48090B", "#540b0e", rev(brewer.pal(9, "YlOrRd")),"white", brewer.pal(9, "Blues"), "#06224C", "#031126", "#020813"))
    
    zCuts <- seq(-5.5,6,0.5)
    
} else if(params$eov == 'chlaWeekly' | params$eov == "MBchla8day_LonPM180"){

    cbar_breaks=c(0.03, 0.1, 0.2, 0.4,  2, 10, 30)
    cbar_limits <- limits <- c(0.03, 30)
    cbar_labels=c(0.03, 0.1, 0.2, 0.4,  2, 10, 30)
    cbar_int <- 0.1
    cbar_title <- 'Chl (mg/m^3) \n'
    
    tzcf_contour = NA #0.2
    tzcf_color = NA #'gray10'
    
    tcms_color = "#FFFCF2"
        
    smooth_rainbow <- khroma::colour("smooth rainbow")

    cpal <- c(smooth_rainbow(length(seq(floor(limits[1]), ceiling(limits[2]), 1)), range = c(0, 0.9)), "#9e2a2b", "firebrick4")

    zCuts <- seq(0,20,1)
}

```

### Get Map Elements
```{r get-map-elements}
# add map elements

## continents
mapdata <- get_mapdata()

## etopo bathy
bathy_df <- get_bathy_df()

## mask GoC from bathy_df
bathy_masked_df <- mask_goc_bathy(df = bathy_df, .poly = goc_mask)

## cclme shapefile
cclme_df <- get_cclme_df()

## us state boundaries
usa <- get_state_borders()

```

```{r assign-cohort1-release-loc}
release_loc = data.frame(lat=39.315, lon=213.9333)
```


### Assign GG Layers
```{r make-gglayers}

add_baseplot <- function(){
    list(
    # add land
    geom_polygon(data = mapdata, aes(x=long, y = lat, group = group), color = "black", fill = "black")
    )
}

add_anim_theme <- function(bbox = params$bbox, subtitle_text_col = "snow"){
    list(
    # theme
    theme_minimal(), 
    theme(
        text = element_text(size=12-2),
        plot.title = element_text(size=14, face="bold", margin=margin(t=20,b=0), hjust=0.03),
        plot.subtitle = element_text(size = 14-2, face="bold", margin=margin(t=30,b=-30), hjust=0.025, color=subtitle_text_col),
        plot.caption = element_text(size=9.5-1.5),
        legend.key = element_rect(color="snow", fill = 'white'), legend.key.size=unit(13-2,"point"),
        legend.text=element_text(size=7.5),
        plot.margin = unit(c(0.75, 0, 0.5, 0), "cm")
    ),

    # set map extent
    coord_sf(xlim = c(make360(bbox$xmin+1), make360(bbox$xmax)), ylim = c(bbox$ymin, bbox$ymax), expand = FALSE, crs = st_crs(4326)),

    # labs
    labs(x = "\n Longitude \n", y = "\n \n Latitude \n ")

    )
}


add_bathy <- function(data = bathy_df, depths = c(-200), cols = c("azure4")){
    list(
    geom_contour(data=data, aes(x=make360(long), y=lat, z = z), colour = cols[1], linewidth = 0.75,
                 breaks = c(depths[1]))
    )
}

add_cclme <- function(data = cclme_df){
    list(
         geom_polygon(data = data, aes(x = make360(long), y = lat.x, group = group), fill = 'gray85', alpha = 0.5) 
    )
}

add_release_location <- function(data = release_loc){
    list(
        geom_point(data=data, aes(x=lon, y=lat), fill = "lightgray", color = "black", shape = 4, size = 5.5)
    )
}

add_tcms_box <- function(tcms_color = "white"){
    list(
         geom_rect(aes(xmin=225,xmax=243,ymin=25.25,ymax=35), colour=tcms_color,alpha=0, size=0.65) 
    )
}

add_tzcf_contour <- function(data = eov_df, tzcf_color, tzcf_contour){
    list(
     # add tzcf contour
    geom_contour(data=data, aes(x=x, y=y, z = val), colour = tzcf_color, linewidth = 1.25,
                 breaks = c(tzcf_contour)) 
    )
    
}

add_state_borders <- function(data = usa){
    list(
        geom_sf(data = data, color = "snow", fill = "black", size=0.5)
    )
}

update_map_extent <- function(bbox = c(-130, -110, 25, 50)){
    list(
        coord_sf(xlim = c(make360(bbox[1]+1), make360(bbox[2])), ylim = c(bbox[3], bbox[4]), expand = FALSE, crs = st_crs(4326))
    )
}

```

```{r}

idColors <-
  setNames( c(rainbow(25))
            , levels(turtles_df_anim$id)  )

add_turtle_pts <- function(data){
    list(
        geom_point(inherit.aes = FALSE, data = data, # point fill color
            aes(x=lon,y=lat, color = as.factor(id)), stroke = 0.75, alpha = 0.90, size=2, show.legend=FALSE),
        # scale_colour_manual(values = rainbow(25)),
        scale_colour_manual(values = setNames(idColors, ids), drop = F),
        
        geom_point(inherit.aes = FALSE, data = data, # point border color
            aes(x=lon,y=lat, color = as.factor(id)), stroke = 0.75, alpha = 0.90, size=2, show.legend=FALSE), 
        # scale_colour_manual(values = rainbow(25))
        scale_colour_manual(values = setNames(idColors, ids), drop = F)
    )
}
           
add_turtle_lines <- function(data){
    list(
        geom_path(data = data,
            aes(x=lon,y=lat, color = as.factor(id), group = as.factor(id)), linewidth = 1.5, show.legend = FALSE),
         scale_colour_manual(values = setNames(idColors, ids), drop = F)
    )
}  

```


```{r}
# chl cpal
add_chl_cpal <- function(limits = cbar_limits, breaks=cbar_breaks, labels=format(cbar_labels), cbar_title){
    list(
        scale_fill_gradientn(trans="log10", colours = cpal[11:length(cpal)], name = cbar_title,
        limits = limits,
        breaks=breaks, labels=labels)
    )
}

# sst cpal
add_sst_cpal <- function(labels = cbar_breaks, cbar_title){
    list(
        scale_fill_manual(values = cpal[7:length(cpal)], name = cbar_title, 
        labels = labels, drop = F, na.translate = F,
        guide = guide_legend(label.vjust=+1.2, barwidth = 1, frame.colour = "black", ticks.colour = "black", ncol =1, reverse=T)) 
    )
}

# ssta cpal
add_ssta_cpal <- function(labels = cbar_breaks, cbar_title){
    list(
        scale_fill_manual(values = cpal[2:length(cpal)], name = cbar_title, 
        labels = cbar_breaks, drop = F, na.translate = F,
        guide = guide_legend(label.vjust=+1.2, barwidth = 1, frame.colour = "black", ticks.colour = "black", ncol =1, reverse=F)) 
    )
}
    
```



### Assign Plot Titles
```{r assign-plot-titles}

if(params$eov == 'sst'){
    title_eov <- 'sea surface temperature (SST)'
    subtitle_text_col <- 'snow'
        caption_iso <- 'The white line represents the 18째C isotherm. '
        eov_source <- 'NOAA Coral Reef Watch 5km Daily SST'
} else if(params$eov == 'ssta'){
    title_eov <- 'sea surface temperature anomaly (SSTA)'
    subtitle_text_col <- 'gray8'
    caption_iso <- ''
    eov_source <- 'NOAA Coral Reef Watch 5km Daily SSTA'

} else if(params$eov == 'chlaWeekly'){
    title_eov <- 'chlorophyll-a (Chl)'
    subtitle_text_col <- 'gray8'
        caption_iso <- '' #'The 0.2 mg/m^3 isopleth (black line) represents the approximate TZCF position in the eastern North Pacific. '
        eov_source <- 'VIIRS Near Real-Time, DINEOF Gap-Filled 9km Weekly Chl Concentration'
        
} else if(params$eov == 'MBchla8day_LonPM180'){
    title_eov <- 'chlorophyll-a (Chl)'
    subtitle_text_col <- 'gray8'
        caption_iso <- '' #'The 0.2 mg/m^3 isopleth (black line) represents the approximate TZCF position in the eastern North Pacific. '
        eov_source <- 'Chlorophyll-a, Aqua MODIS, Weekly Composite 0.025째 Chl Concentration'
        
} else if(params$eov == 'current'){
    title_eov <- 'surface current flow'
    subtitle_text_col <- 'gray8'
        caption_iso <- 'The 0.2 mg/m^3 isopleth (black line) represents the approximate TZCF position in the eastern North Pacific. '
        eov_source <- 'Calculated from Near Real-Time Geostrohic Current (u, v) 0.2 degrees spatial res, Daily'
}

```

```{r}

anim_title <- str_c("STRETCH ", str_to_title(params$timestep), " turtle movements (n=25) with ", title_eov)

# anim_caption = str_c("\n Raw tracking data from ARGOS averaged to 1 " , params$timestep , " location per turtle (circles)\n\n", 
#                          "California Current Large Marine Ecosystem (CCLME) shaded in gray\n", 
#                          "Thermal Corridor region (box). Ship release location (X)\n",
#                           caption_iso, "Continental depths of 200m (gray lines)\n",
#                          "\n Data source: ", eov_source," \n Dana Briscoe"
#                                  )

anim_caption = str_c("\n Raw tracking data from ARGOS averaged to 1 " , params$timestep , " location per turtle (circles)\n\n", 
                         "California Current Large Marine Ecosystem (CCLME) shaded in gray\n", 
                         "Continental depths of 200m (gray lines). Ship release location (X)\n",
                          caption_iso, "Thermal Corridor region (box)\n",
                         "\n Data source: ", eov_source," \n Dana Briscoe"
                                 )
```



### Set CC-EOV Daily/Weekly Timestep
```{r set-dates-for-anim}

if(identical(unique(turtles_df_anim$date),unique(eov_df_anim$date))){
    
    if (params$timestep == 'daily'){

    dates <- seq(as.Date(params$enddate %m+% months(-1)), as.Date(params$enddate), by = "1 day")
    
    } else if (params$timestep == 'weekly' & params$eov != "MBchla8day_LonPM180"){

    # dates <- seq(as.Date(min(turtles_df_weekly$date)), as.Date(max(turtles_df_weekly$date)-1), by = "weeks") # assumes using end of week: week -1
    dates <- seq(as.Date(min(turtles_df_weekly$date)), as.Date(max(turtles_df_weekly$date)), by = "weeks") # assumes start of week

    } else if (params$timestep == "weekly" & params$eov == "MBchla8day_LonPM180"){
     dates <- seq(as.Date('2023-12-03'), as.Date(max(turtles_df_weekly$date)), by = "weeks") # assumes start of week
    }

    n = length(dates)
    
} else {
    print('error. turtle-eov dates do not match.')
}

```

## Plot Frames
```{r lapply-tracks-plot-list}

tracks_plot_list <- 
    lapply(seq(1,n), function(i) {

        eov_frame = eov_df_anim %>% filter(date == dates[i]) 
        turtles_frame = turtles_df_anim %>% filter(date <= dates[i]) 
        
        # if(params$timestep == 'daily'){
        #     startdate <- params$enddate %m+% months(-1)
        #     turtles_frame = turtles_df_anim %>% filter(date >= startdate & date <= dates[i]) 
        # } else if(params$timestep == 'weekly'){
        #     turtles_frame = turtles_df_anim %>% filter(date <= dates[i]) 
        # }
        
        # plot up
            ggplot() +
                
            # add eov raster    
            {        
                if (params$eov =='sst' | params$eov == 'ssta'){        
                    ## for discrete color pal ---        
                    geom_contour_filled(data = eov_frame %>% subset(!is.na(val)) ,
                                        aes(x = x, y = y, z = val, group = date), breaks = seq(cbar_limits[1],cbar_limits[2],cbar_int)) 
                } else if (params$eov =='chlaWeekly' | params$eov =='MBchla8day_LonPM180') {  
                    ## for continuous color pal---                    
                    geom_raster(data = eov_frame,
                                aes(x = x, y = y, fill = val, group = date), interpolate = TRUE) 
                }
                
            }  +   
                
            # add bathy
                {
                    if (params$bathy) {
                        add_bathy(data = bathy_masked_df, depths = c(-200), )
                    }
                } +
                
            # add tzcf contour
            {
                if (!is.null(tzcf_contour)) {
                   add_tzcf_contour(data = eov_frame, tzcf_color, tzcf_contour)
                }
                
            } +
            
            # add coast 
            add_baseplot() +
                
            # add state borders
            {
                if (!is.null(params$state_borders)) {
                  add_state_borders()
                }
                
            } +
                
             # add cclme
            {
                if (!is.null(params$cclme)) {
                  add_cclme()
                }
                
            } +
             
            # add tcms box
            {
                if (params$tcms){
                    add_tcms_box(tcms_color)
                }
                
            } +
            
            # add colorbar    
                {
                if (params$eov =='chlaWeekly' | params$eov == "MBchla8day_LonPM180"){
                    
                   add_chl_cpal(limits = cbar_limits, breaks=cbar_breaks, labels=format(cbar_labels), cbar_title)
                    
                } else if (params$eov =='sst') {
                    
                  add_sst_cpal(labels = cbar_breaks, cbar_title)    
                    
                } else if (params$eov =='ssta') {
                    
                  add_ssta_cpal(labels = cbar_breaks, cbar_title) 
                }
                    
            } +
                
            # turtle points -- wc pal
            add_turtle_pts(data = turtles_frame %>% filter(date == dates[i]) %>% mutate(lon = make360(lon))) +
                
            add_turtle_lines(data = turtles_frame %>% mutate(lon = make360(lon))) +
                
                
            # dynamic labs
            {
               if (params$timestep == 'daily'){
                    labs(subtitle = str_c("Date: ", format(dates[i], "%b-%d-%Y"))) 
                } else if (params$timestep == 'weekly'){    
                    labs(subtitle = str_c("Week of: ", format(dates[i], "%b-%d-%Y")))
                }
            } +
                
            # labs(title = anim_title,
            #      caption = anim_caption
            #      ) +
                
        # add custom theme for anim frames
        add_anim_theme(bbox = params$bbox, subtitle_text_col = subtitle_text_col)
            
    })
                
```


```{r set-plot-list-names}
# name the elements in the list
wk_names <- str_c("plot_", unique(dates))
names(tracks_plot_list) <- wk_names

```

### Resize Legend
```{r resize-cbar}
# resize colorbar
panel_height <- unit(1,"npc") - sum(ggplotGrob(tracks_plot_list[[1]])[["heights"]][-3]) - unit(1,"line")
# panel_height <- unit(1.5,"npc") - sum(ggplotGrob(tracks_plot_list[[1]])[["heights"]][-3]) - unit(1,"line")
chl_panel_height <- unit(1,"npc") - sum(ggplotGrob(tracks_plot_list[[1]])[["heights"]][-5]) - unit(1,"line")

# apply new height to indiv plot frames

tracks_plot_list <- 
    lapply(seq(1,n), function(i) {
        tracks_plot_list[[i]] <- tracks_plot_list[[i]] + 
            
            {        
                if (params$eov =='sst'){   
                    guides(fill = guide_legend(title = cbar_title, ncol=1, reverse=T, barheight = panel_height, limits = cbar_breaks,
                                               ticks = TRUE)) 
                } else if(params$eov == 'ssta')  {
                    guides(fill = guide_legend(title = cbar_title, ncol=1, reverse=T, barheight = panel_height, limits = cbar_breaks,
                                               ticks = TRUE))   
                }  else if (params$eov == 'chlWeekly' | params$eov == 'MBchla8day_LonPM180' & !params$subset_tcms) {
                    guides(fill = guide_colourbar(barheight = panel_height, ticks = TRUE))
                    
                } else if (params$eov == 'chlWeekly' | params$eov == 'MBchla8day_LonPM180' & params$subset_tcms) {
                    guides(fill = guide_colourbar(barheight = chl_panel_height, ticks = TRUE))
                }
            } +
            
            {
                if(params$subset_tcms){
                    # add_bathy(data = bathy_df, depths = c(-200), cols = c("azure4")) +
                    update_map_extent(bbox = c(-138, -110, 25, 37))
                }
            } +
            
            labs(title = anim_title, caption = anim_caption) 
    })

```


## Save Frames
```{r}
# save plots as pngs (to create gif)
save_figs = TRUE

dir <- str_c('../anim_figs/', params$timestep, '_anim')
if(params$subset_tcms){
    p_extent <- 'tcms_region'
} else {
    p_extent <- 'enpac'
}    


if(save_figs){
    lapply(seq(1:length(wk_names)), function(i) { ggsave(tracks_plot_list[[i]], 
                                                         file = str_c(dir, '/', i, "_", dates[i], "_", params$eov, "_tracks_", p_extent,".png"), 
                                                         width=14,
                                                         # height=8.5,   # comment out height to get auto aspect ratio set!
                                                         bg = 'white')
    })
}

```

## Movie Time
### Sort Files in Chron Order
```{r}
# create movie
library(gtools)

# List plots files
flist <- list.files(dir, pattern = "_tracks",full.names=T)
plot_files <- flist[grepl(str_c(params$eov,"_"), flist, fixed=TRUE)] 
pfiles <- plot_files[order(basename(plot_files))]

pfiles <- gtools::mixedsort(pfiles)

```

# Crop PNG Frames
```{r }
# #intermediate step to crop PNG file and reduce negative space

## use crop image source function ------
source('crop_image.R')
crop_image(pfiles)

```

### Animate as GIF
```{r animate-gif}
# Read the plots as image
plots_list <- lapply(pfiles, image_read)

# Join the list of plots
plot_joined <- image_join(plots_list)

# Create animation, defining the frames per second (fps)
if(params$timestep == 'daily'){
    plot_animated <- image_animate(plot_joined, fps = 2)
} else if (params$timestep == 'weekly'){
    plot_animated <- image_animate(plot_joined, fps = 1)
}

# Write animation as gif
image_write(image = plot_animated,
            path = str_c(dir, "stretch_2023_",params$timestep,"_animation_", params$enddate, "_", params$eov,"_", p_extent ,".gif"))


## Use CONVERTIO online for mp4 generation
```

